### ISSUE TITLE
hit delete doesn't remove hit from the local Hits database table

### ISSUE THREAD

**Issue by gureckis** [NYUCCL/psiTurk#521] opened 2021-06-29 14:51 UTC
when you delete a hit it deletes it from the AMT site using Boto but the hit will remain the Hit database table.  seem like it should be deleted from the local table as well?

**Comment by deargle** [comment] 2021-06-29 17:41
I think we want to leave it in there, although I'd have to think about it.
It's used to decide which participants are part of the "current study".

**Comment by deargle** [comment] 2021-10-01 20:22
Can you explain what your use-case is where you need it to be deleted from the table? With the code written as it is right now, It needs to stay in the local table, even if the hit is deleted from mturk, for paticipant-querying purposes.

**Comment by deargle** [comment] 2022-02-28 20:25
Closing because it's the intended behavior for hit-ids to not be removed from the hit table. Although granted, the purpose of the table isn't explained anywhere in the docs.

**Closed by deargle** 2022-02-28 20:25 UTC
Labels: unexpected
