### ISSUE TITLE
Experiment doesn't work at all

### ISSUE THREAD

**Issue by fspinar** [NYUCCL/psiTurk#525] opened 2021-08-11 18:06 UTC
Hi all,

I am trying to run my experiment by using jsPsych. The code works fine when I run it as an HTML code separate from psiTurk, but when I try to run it on mTurk sandbox or in the debug mode of psiTurk, I only get a blank screen. I also do not observe and error on the server.log file. It only shows :
2021-08-11 13:01:28,921 Scheduler started
Although in earlier runs I had the following 

sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  too many connections for role "pfmlaacusymlql"

(Background on this error at: http://sqlalche.me/e/13/e3q8)

Could you help me through this ? I can't run it on psiTurk although I can run it as an .html code.

Thanks a lot.

**Comment by deargle** [comment] 2021-08-16 19:26
I'm not sure how to help here. I'm going to close this "issue" since it's not a psiturk bug -- it's an error somewhere in your implementation. You can try opening something in the new "discussions" area, https://github.com/NYUCCL/psiTurk/discussions

* Blank screens on webpages sometimes are caused by javascript errors. Web browsers have javascript error consoles. Javascript errors would not (could not) appear in the server.log file.
*  "running HTML code in psiturk" is a confusing phrase. psiturk is a flask app.

Beyond those general tips, I can't help without you providing enough details for someone to exactly replicate the error you're seeing.

**Closed by deargle** 2021-08-16 19:26 UTC

**Comment by fspinar** [comment] 2021-08-17 10:10
Thanks @deargle . This is my first experience with javascript,html, PsiTurk, jsPsych... I didn't even know about javascript error consoles. 

I will look into it in more detail.

Thanks.

**Comment by fspinar** [comment] 2021-09-10 20:35
Hello again @deargle 

I looked into the web browser's log file, and I got "uncaught reference error, jsPsych is not defined". This happens when I first attempted to use jsPsych in my code. This is despite the fact that I have jsPsych under : jsPsych under ~/static/js/jspych. Any idea as to why jsPsych is not recognized ? 

Thanks a lot.

**Comment by deargle** [comment] 2021-09-10 21:24
That's a basic javascript and jspsych question -- seek the help of a
javascript tutor.
