### ISSUE TITLE
Cannot test HITs multiple times with the same worker

### ISSUE THREAD

**Issue by mimilab02** [NYUCCL/psiTurk#434] opened 2020-08-24 04:55 UTC
I am trying to test my HIT in the sandbox environment, but I cannot test the HIT more than once with the same worker. I keep getting the error: 

"Sorry, our records indicate that you have already completed....Because this is a Psychology experiment, you can only complete this HIT once...
Error: #1010"

I've tried deleting all records of the worker ID from the database, setting allow_repeats to True in the config file, and deleting the HIT and posting a new one, but I'm still running into the same error. (If I create a new worker account and test the HIT, it works perfectly but I can't create new accounts each time I want to test.)

**Comment by deargle** [comment] 2020-08-24 05:01
Suspect you're not deleting from the correct database, because if you
actually deleted the records, it should allow another run. Perhaps you
didn't switch away from a sqlite db, perish the thought?

**Comment by mimilab02** [comment] 2020-08-27 01:18
I'm deleting it from the default sqlite db, but I'm not actively using it to save my other experiment data (directly saving it to a file on the web server instead). Worker ID is not saved anywhere else I believe. Might there be another issue?

**Comment by deargle** [comment] 2020-08-27 02:11
I dont follow your description of your setup, but no, that's the most
likely explanation. You should not be using sqlite for production (or
sandbox). My guess is still that your code is creating another version of
that db wherever the experiment server is actually running.

**Comment by mimilab02** [comment] 2020-08-27 08:18
Ahh I see, I mean that I'm not using a database at all and not saving worker ids - wouldn't that not affect workers from redoing the task?

**Comment by Portll** [comment] 2020-08-28 00:09
We mean that as psiTurk creates a database when one is not specified
properly you're probably not looking in the right place. I suggest closing
this fix request because it's not a bug, going back to the documentation
and learning how to set it up by creating an empty, static database you can
use, then using a tool like SQLYog Community Edition (for MySQL) to delete
your test workerIDs once you've set up your production instance and tested
it sufficiently.

While the SQLite database option is present it's not expected that people
will prefer to use it for most development/testing and production/live
instances and experiments.

Lastly, as helpful as people are here, this is not a bug you're reporting,
and nor is it a support forum for your particular instance! Trying a new
instance with a static database, then using the Google Group at
https://groups.google.com/forum/m/#!forum/psiturk or offering to pay the
project creator for help (todd.gureckis/at/nyu.edu) if you get stuck would
be my suggested next steps.

John Hancock

**Comment by deargle** [comment] 2020-08-28 16:33
Wait, people pay _money_ for this?! I'm sure @gureckis wouldn't want any, just send it all to me 😛 

@Portll is correct that this isn't a bug in the code, and he's also correct that google-groups would be a better place for help request. I haven't been guiding people that direction, but I can do so in the future to keep github traffic down for community users who would prefer them separate. This issue raised by @mimilab02 does point to a meta organization-level problem in that the docs aren't as good as they could be. Todo.

@mimilab02, psiturk _has_ to use a database to work. It uses one to keep track of participants, to block repeats. etc. That's why you're being blocked from taking it again. If you accessed the database that your instance is using, you would be able to delete the record with your worker_id, and take it again.

**Closed by deargle** 2020-08-28 16:33 UTC
